#############################################################################
# Tr8n Configuration
#
# Default settings for all environments
# 
# You can overload any feature for any environment by changing the 
# environment settings at the bottom of the file. 
#
# Alternatively, you can overload any of the methods of Tr8n::Config
#############################################################################

defaults: &defaults
  enable_tr8n:                true      # enables the engine
  enable_key_source_tracking: false     # builds the site map sources
  enable_key_caller_tracking: false     # tracks all calls to labels
  
  enable_glossary_hints:      true      # shows glossary in the translator    
  enable_software_keyboard:   true      # shows the soft keyboard icon  
  enable_google_suggestions:  true      # uses google for suggestions
  enable_keyboard_shortcuts:  true      # adds some keyboard shortcuts 
  enable_dictionary_lookup:   true      # shows dictionary words definitions 
  
  #############################################################################
  # Set the following flag to true if you would like to allow any registered 
  # user to become a translator. The users become translators as soon as they
  # enable inline translation mode, submit a translation, or vote on a 
  # translation. If the flag is set to false, then a user must be promoted to
  # be a translator in order to submit or vote on translations.
  #############################################################################
  open_registration_mode:     true

  #############################################################################
  # If you would like to run tr8n on a different database, 
  # you can overload the remote setting and provide the database details
  # for each environment by using a database symbol.
  # 
  # use_remote_database:        true
  # database:
  #   host:                     localhost
  #   database:                 tr8n
  #   adapter:                  postgresql
  #   username:                 tr8n
  #   password:
  #   port:                     5432
  #   encoding:                 utf8  
  #############################################################################
  use_remote_database:        false

  #############################################################################
  # Tr8n best run with caching enabled 
  # You can configure cache adapter and store parameters by providing the 
  # the name of your class implementation and the store settings. 
  #
  # For example: 
  #  
  # cache_adapter:  ActiveSupport::Cache
  # cache_store:    memory_store
  # cache_store:    file_store
  # cache_store:    drb_store
  # cache_store:    [mem_cache_store, 'localhost:11211']
  #
  # You can also provide your own implementation of the adapter:
  #
  # cache_adapter:  YOUR_CACHE_ADAPTER_CLASS
  #
  #############################################################################
  enable_caching:             false
  cache_adapter:              ActiveSupport::Cache
  cache_store:                [mem_cache_store, 'localhost:11211']
  cache_version:              1 # you can change the version to invalidate it

  #############################################################################
  # By default, Tr8n will use its own logger. If you set it to false,  
  # it will use default Rails logger.
  #############################################################################
  use_tr8n_logger:            true
  tr8n_log_path:              log/tr8n.log      # location of the log file
  enable_paranoia_mode:       true              # logs every translator action

  #############################################################################
  # Site Integration Settings
  #############################################################################
  site_info:  
    current_user_method:      current_user          # provides current user object
    current_locale_method:    current_locale        # provides current locale
    title:                    Tr8n                  # site title, for customization 
    default_url:              /home         
    default_locale:           en-US
    sitemap_json:             /config/tr8n/default_sitemap.json
    splash_screen:            /tr8n/common/splash_screen
    admin_layout:             admin
    tr8n_layout:              application
    user_info:  
      enabled:                true
      class_name:             User
      methods:  
        id:                   id
        name:                 name
        admin:                admin?
        guest:                guest?
        mugshot:              mugshot
        link:                 link
        locale:               locale
        
  #############################################################################
  # Rules Engine Settings
  #############################################################################
  rules_engine:  
    language_rule_classes:    [Tr8n::NumericRule, Tr8n::GenderRule, Tr8n::GenderListRule, Tr8n::DateRule]
    numeric_rule:  
      token_suffixes:         [count, num, age, hours, minutes, years, seconds]
      object_method:          to_i
    gender_rule:  
      token_suffixes:         [user, profile, actor, target, partner, parent, child, sibling, manager]
      object_method:          gender
      method_values:  
        female:               female
        male:                 male
        neutral:              neutral
        unknown:              unknown
    gender_list_rule:         # works together with gender rule 
      object_method:          size
      token_suffixes:         [list]
    date_rule:                # date rule
      object_method:          to_date
      token_suffixes:         [date]
    
    # minimal rank makes the translation acceptable for subsitution and counts towards the translator rank
    translation_threshold:    1
    
    viewing_user_token:       viewing_user
    translation_rank_styles:  
      -1000..-5:              color:red;font-weight:bold;
      -4..-1:                 color:red;
      1..10:                  color:green;
      11..1000:               color:green;font-weight:bold;
  
  #############################################################################
  # API Settings
  #############################################################################
  api:  
    enabled:                  true
    response_encoding:        json     # options: xml, json
    allow_key_registration:   true

  #############################################################################
  # Localization Settings
  #############################################################################
  localization:  
    default_day_names:        [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
    default_abbr_day_names:   [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    default_month_names:      [January, February, March, April, May, June, July, August, September, October, November, December]
    default_abbr_month_names: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
    custom_date_formats:  
      default:                '%m/%d/%Y'            # 07/4/2008
      short_numeric:          '%m/%d'               # 07/4
      short_numeric_year:     '%m/%d/%y'            # 07/4/08
      long_numeric:           '%m/%d/%Y'            # 07/4/2008
      verbose:                '%A, %B %d, %Y'       # Friday, July  4, 2008
      monthname:              '%B %d'               # July 4
      monthname_year:         '%B %d, %Y'           # July 4, 2008
      monthname_abbr:         '%b %d'               # Jul 4
      monthname_abbr_year:    '%b %d, %Y'           # Jul 4, 2008
      date_time:              '%m/%d/%Y at %H:%M'   # 01/03/1010 at 5:30
 
#############################################################################
# Environment Settings
# You can overload any feature defined in the defaults for any environment
#############################################################################
development:
  <<: *defaults
  enable_key_source_tracking: true
  
test:
  <<: *defaults
  enable_tr8n:                false 
      
qa:
  <<: *defaults
  enable_key_source_tracking: true

stage:
  <<: *defaults
  
  enable_key_source_tracking: true

production:
  <<: *defaults

  enable_key_source_tracking: false

#  an example of how to overload the databse settings for production 
#  use_remote_database:        true
#  database:
#    host:                     localhost
#    database:                 tr8n
#    adapter:                  postgresql
#    username:                 tr8n
#    password:
#    port:                     5432
#    encoding:                 utf8  
#
#  alternatively you can specify it by referencing an existing database config
#  database:                   production1 
