#############################################################################
#
# Tr8n Default Date Rules
#
#############################################################################

en-US: 
  rule1:
    operator:   is_in
    value:      past
  rule2:
    operator:   is_in 
    value:      future
  rule3:
    operator:   is_in 
    value:      present
